from __future__ import annotations

import argparse
import os
from pathlib import Path
import sys


CONFIG_PATH = Path("config/echo-calendar.config.env")


def parse_key_values(path: Path) -> dict[str, str]:
    values: dict[str, str] = {}
    if not path.is_file():
        return values

    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        values[key.strip()] = value.strip()
    return values


def require_value(values: dict[str, str], key: str) -> str:
    value = values.get(key, "").strip()
    if not value:
        raise SystemExit(f"Missing required config key: {key}")
    return value


def value(values: dict[str, str], key: str, default: str = "") -> str:
    return values.get(key, default).strip()


def expand_local_path(raw: str, repo_root: Path) -> str:
    expanded = raw.strip().strip("\"").strip("'")
    userprofile = os.environ.get("USERPROFILE", "").strip()
    if not userprofile:
        parts = repo_root.resolve().parts
        if len(parts) >= 5 and parts[1].lower() == "mnt" and parts[3].lower() == "users":
            userprofile = f"{parts[2].upper()}:\\Users\\{parts[4]}"
    replacements = {
        "%USERPROFILE%": userprofile,
        "%HOMEDRIVE%": os.environ.get("HOMEDRIVE", "").strip(),
        "%HOMEPATH%": os.environ.get("HOMEPATH", "").strip(),
    }
    for marker, replacement in replacements.items():
        if replacement:
            expanded = expanded.replace(marker, replacement)
    return os.path.expandvars(expanded)


def local_output_path(raw: str, repo_root: Path) -> Path:
    expanded = expand_local_path(raw, repo_root)
    if os.name != "nt" and len(expanded) >= 3 and expanded[1] == ":" and expanded[2] in {"\\", "/"}:
        drive = expanded[0].lower()
        rest = expanded[3:].replace("\\", "/")
        return Path("/mnt") / drive / rest
    return Path(expanded)


def positive_int(values: dict[str, str], key: str) -> str:
    raw = require_value(values, key)
    if not raw.isdigit() or int(raw) <= 0:
        raise SystemExit(f"{key} must be a positive integer")
    return raw


def render_app_client_config(values: dict[str, str]) -> str:
    server_base_url = require_value(values, "SERVER_BASE_URL").rstrip("/")
    version_code = positive_int(values, "APP_VERSION_CODE")
    version_name = require_value(values, "APP_VERSION_NAME")
    lines = [
        "# Generated by config/scripts/sync_config.py from config/echo-calendar.config.env.",
        "# Edit the source config file, not this generated file.",
        "",
        "SERVER_BASE_URL=" + server_base_url,
        "APP_VERSION_CODE=" + version_code,
        "APP_VERSION_NAME=" + version_name,
        "",
        "AI_API_TIMEOUT_MS=" + value(values, "AI_API_TIMEOUT_MS", "30000"),
        "HOLIDAY_SYNC_TIMEOUT_MS=" + value(values, "HOLIDAY_SYNC_TIMEOUT_MS", "5000"),
        "ALLOW_SIGNUP=" + value(values, "ALLOW_SIGNUP", "false"),
        "AI_SEND_CLIENT_API_KEY_DEBUG=" + value(values, "AI_SEND_CLIENT_API_KEY_DEBUG", "false"),
        "AI_SEND_CLIENT_API_KEY_RELEASE=" + value(values, "AI_SEND_CLIENT_API_KEY_RELEASE", "false"),
        "AI_REQUIRE_HTTPS_DEBUG=" + value(values, "AI_REQUIRE_HTTPS_DEBUG", "false"),
        "AI_REQUIRE_HTTPS_RELEASE=" + value(values, "AI_REQUIRE_HTTPS_RELEASE", "true"),
    ]
    return "\n".join(lines) + "\n"


def render_app_signing_path(values: dict[str, str]) -> str:
    signing_path = require_value(values, "APP_SIGNING_CONFIG_PATH")
    lines = [
        "# Generated by config/scripts/sync_config.py from config/echo-calendar.config.env.",
        "# This points Gradle to a local signing file outside the git repo.",
        "",
        "SIGNING_CONFIG_FILE_PATH=" + signing_path,
    ]
    return "\n".join(lines) + "\n"


def render_server_dotenv(values: dict[str, str], repo_root: Path) -> str:
    lines = [
        "# Generated by config/scripts/sync_config.py from config/echo-calendar.config.env.",
        "# Docker Compose reads this file automatically in the server/ folder.",
        "",
        "BACKEND_EXTERNAL_ENV_PATH=" + expand_local_path(require_value(values, "BACKEND_EXTERNAL_ENV_PATH"), repo_root),
        "CLOUDFLARED_DIR=" + expand_local_path(require_value(values, "CLOUDFLARED_DIR"), repo_root),
        "BACKEND_DATA_DIR=" + expand_local_path(require_value(values, "BACKEND_DATA_DIR"), repo_root),
        "BACKEND_DOWNLOADS_DIR=" + expand_local_path(require_value(values, "BACKEND_DOWNLOADS_DIR"), repo_root),
        "BACKEND_LOGS_DIR=" + expand_local_path(require_value(values, "BACKEND_LOGS_DIR"), repo_root),
    ]
    return "\n".join(lines) + "\n"


SERVER_DEFAULT_KEYS = (
    "HOST",
    "PORT",
    "SERVER_MODE",
    "OPENAI_MODEL",
    "LLM_TIMEOUT_SECONDS",
    "LLM_MAX_RETRIES",
    "LLM_DEADLINE_SECONDS",
    "LLM_MAX_OUTPUT_TOKENS",
    "RATE_LIMIT_PER_MINUTE",
    "BLOCK_PROBE_REQUESTS",
    "ALLOW_SIGNUP",
    "KOREA_HOLIDAY_API_BASE_URL",
    "KOREA_HOLIDAY_API_TIMEOUT_SECONDS",
    "KOREA_HOLIDAY_API_MAX_CONCURRENCY",
    "HOLIDAY_DB_PATH",
    "USAGE_DB_PATH",
    "KAFKA_ENABLED",
    "KAFKA_BOOTSTRAP_SERVERS",
    "KAFKA_USAGE_TOPIC",
    "KAFKA_USAGE_GROUP_ID",
    "KAFKA_CLIENT_ID",
    "HOLIDAY_SYNC_ENABLED",
    "HOLIDAY_BOOTSTRAP_START_DATE",
    "HOLIDAY_BOOTSTRAP_FORWARD_YEARS",
    "HOLIDAY_DAILY_WINDOW_YEARS",
    "APP_MIN_SUPPORTED_VERSION_CODE",
    "APP_DOWNLOADS_DIR",
    "APP_APK_FILENAME",
    "APP_APK_DOWNLOAD_URL",
)


def render_docker_defaults(values: dict[str, str], min_supported: str | None = None) -> str:
    output: list[str] = [
        "# Generated by config/scripts/sync_config.py from config/echo-calendar.config.env.",
        "# Safe Docker defaults. Secrets and production overrides belong in the external env file.",
        "",
    ]
    for key in SERVER_DEFAULT_KEYS:
        if key == "APP_MIN_SUPPORTED_VERSION_CODE" and min_supported is not None:
            output.append(f"{key}={min_supported}")
        else:
            output.append(f"{key}={value(values, key)}")
        if key in {"SERVER_MODE", "LLM_MAX_OUTPUT_TOKENS", "ALLOW_SIGNUP", "KOREA_HOLIDAY_API_MAX_CONCURRENCY", "USAGE_DB_PATH", "KAFKA_CLIENT_ID", "HOLIDAY_DAILY_WINDOW_YEARS"}:
            output.append("")

    output.extend(
        [
            "APP_LATEST_VERSION_CODE=" + positive_int(values, "APP_VERSION_CODE"),
            "APP_LATEST_VERSION_NAME=" + require_value(values, "APP_VERSION_NAME"),
            "",
            "OPENAI_API_KEY=",
            "KOREA_HOLIDAY_API_KEY=",
            "USAGE_DASHBOARD_OWNER_USERNAME=",
            "USAGE_DASHBOARD_ACCESS_KEY=",
            "USAGE_ADMIN_USERNAME=",
            "USAGE_ADMIN_PASSWORD=",
        ]
    )
    return "\n".join(output).rstrip() + "\n"


def render_server_external_template(values: dict[str, str], min_supported: str | None = None) -> str:
    version_code = positive_int(values, "APP_VERSION_CODE")
    version_name = require_value(values, "APP_VERSION_NAME")
    min_code = min_supported or value(values, "APP_MIN_SUPPORTED_VERSION_CODE", "1")
    lines = [
        "# Echo Calendar backend external env template",
        "# Copy this file to the external path configured by BACKEND_EXTERNAL_ENV_PATH,",
        "# then fill in the secrets and production overrides for this machine.",
        "",
        "OPENAI_API_KEY=sk-xxxx",
        "KOREA_HOLIDAY_API_KEY=",
        "",
        "OPENAI_MODEL=" + value(values, "OPENAI_MODEL", "gpt-5-nano"),
        "LLM_TIMEOUT_SECONDS=" + value(values, "LLM_TIMEOUT_SECONDS", "40"),
        "LLM_MAX_RETRIES=" + value(values, "LLM_MAX_RETRIES", "0"),
        "LLM_DEADLINE_SECONDS=" + value(values, "LLM_DEADLINE_SECONDS", "60"),
        "LLM_MAX_OUTPUT_TOKENS=" + value(values, "LLM_MAX_OUTPUT_TOKENS", "256"),
        "",
        "RATE_LIMIT_PER_MINUTE=" + value(values, "RATE_LIMIT_PER_MINUTE", "60"),
        "BLOCK_PROBE_REQUESTS=" + value(values, "BLOCK_PROBE_REQUESTS", "true"),
        "ALLOW_SIGNUP=" + value(values, "ALLOW_SIGNUP", "false"),
        "",
        "KOREA_HOLIDAY_API_BASE_URL=" + value(values, "KOREA_HOLIDAY_API_BASE_URL"),
        "KOREA_HOLIDAY_API_TIMEOUT_SECONDS=" + value(values, "KOREA_HOLIDAY_API_TIMEOUT_SECONDS", "8"),
        "KOREA_HOLIDAY_API_MAX_CONCURRENCY=" + value(values, "KOREA_HOLIDAY_API_MAX_CONCURRENCY", "6"),
        "",
        "HOLIDAY_DB_PATH=" + value(values, "HOLIDAY_DB_PATH", "data/holiday_cache.db"),
        "USAGE_DB_PATH=" + value(values, "USAGE_DB_PATH", "data/usage.db"),
        "",
        "USAGE_DASHBOARD_OWNER_USERNAME=",
        "USAGE_DASHBOARD_ACCESS_KEY=",
        "USAGE_ADMIN_USERNAME=",
        "USAGE_ADMIN_PASSWORD=",
        "",
        "HOLIDAY_SYNC_ENABLED=" + value(values, "HOLIDAY_SYNC_ENABLED", "true"),
        "HOLIDAY_BOOTSTRAP_START_DATE=" + value(values, "HOLIDAY_BOOTSTRAP_START_DATE", "1970-01-01"),
        "HOLIDAY_BOOTSTRAP_FORWARD_YEARS=" + value(values, "HOLIDAY_BOOTSTRAP_FORWARD_YEARS", "5"),
        "HOLIDAY_DAILY_WINDOW_YEARS=" + value(values, "HOLIDAY_DAILY_WINDOW_YEARS", "1"),
        "",
        "APP_LATEST_VERSION_CODE=" + version_code,
        "APP_LATEST_VERSION_NAME=" + version_name,
        "APP_MIN_SUPPORTED_VERSION_CODE=" + min_code,
        "APP_DOWNLOADS_DIR=" + value(values, "APP_DOWNLOADS_DIR", "downloads"),
        "APP_APK_FILENAME=" + value(values, "APP_APK_FILENAME", "echo_calendar.apk"),
        "APP_APK_DOWNLOAD_URL=" + value(values, "APP_APK_DOWNLOAD_URL", ""),
    ]
    return "\n".join(lines) + "\n"


def render_runtime_version(values: dict[str, str], min_supported: str | None = None) -> str:
    min_code = min_supported or value(values, "APP_MIN_SUPPORTED_VERSION_CODE", positive_int(values, "APP_VERSION_CODE"))
    lines = [
        "APP_LATEST_VERSION_CODE=" + positive_int(values, "APP_VERSION_CODE"),
        "APP_LATEST_VERSION_NAME=" + require_value(values, "APP_VERSION_NAME"),
        "APP_MIN_SUPPORTED_VERSION_CODE=" + min_code,
    ]
    return "\n".join(lines) + "\n"


def build_outputs(repo_root: Path, values: dict[str, str], sync_min_supported: bool) -> dict[Path, str]:
    min_supported = positive_int(values, "APP_VERSION_CODE") if sync_min_supported else None
    external_downloads_dir = local_output_path(require_value(values, "BACKEND_DOWNLOADS_DIR"), repo_root)
    return {
        repo_root / "app" / "APP_CLIENT_CONFIG.txt": render_app_client_config(values),
        repo_root / "app" / "APP_SIGNING_PATH.txt": render_app_signing_path(values),
        repo_root / "server" / ".env": render_server_dotenv(values, repo_root),
        repo_root / "server" / "docker.defaults.env": render_docker_defaults(values, min_supported),
        repo_root / "server" / "SERVER_ENV_TEMPLATE.env": render_server_external_template(values, min_supported),
        external_downloads_dir / "app_version.env": render_runtime_version(values, min_supported),
    }


def write_outputs(outputs: dict[Path, str], check: bool) -> bool:
    changed = False
    for path, content in outputs.items():
        current = path.read_text(encoding="utf-8") if path.is_file() else None
        if current == content:
            print(f"[sync-config] already-synced: {path}")
            continue
        changed = True
        if check:
            print(f"[sync-config] would-update: {path}")
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        print(f"[sync-config] updated: {path}")
    return changed


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        description="Sync generated Echo Calendar config files from config/echo-calendar.config.env."
    )
    parser.add_argument("--check", action="store_true", help="Only check whether generated files are up to date.")
    parser.add_argument(
        "--sync-min-supported",
        action="store_true",
        help="Legacy option: generate APP_MIN_SUPPORTED_VERSION_CODE from APP_VERSION_CODE for this run.",
    )
    args = parser.parse_args(argv)

    repo_root = Path(__file__).resolve().parents[2]
    config_path = repo_root / CONFIG_PATH
    values = parse_key_values(config_path)
    if not values:
        raise SystemExit(f"Config file not found or empty: {config_path}")

    outputs = build_outputs(repo_root, values, args.sync_min_supported)
    changed = write_outputs(outputs, args.check)
    if args.check and changed:
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
